### ISSUE TITLE
Clone và chạy project tại local

### ISSUE THREAD

**Issue by AmbroseNTK** [Runway-Club/codeathon#1]
Mỗi bạn trong nhóm tiến hành:
1. Fork project
2. Clone về local
3. Đọc và check môi trường thực thi
4. Chạy thử và chụp các ảnh giao diện

Task này giúp các bạn nắm được những tính năng mà project đang có.

@KhanhNoober

**Comment by Shyren12** [comment]
![image](https://user-images.githubusercontent.com/121025871/227791292-2b1e7d36-2f45-43ea-ad56-910f2d394597.png)

**Comment by Shyren12** [comment]
![image](https://user-images.githubusercontent.com/121025871/227791347-2b3584ec-f879-4366-b1b9-94418e17c395.png)

![image](https://user-images.githubusercontent.com/121025871/227791412-ad6926d4-2cac-4741-b97b-5a56e3a682c7.png)
