### ISSUE TITLE
Clone và chạy project tại local

### ISSUE THREAD

**Issue by manhvipro123** [Runway-Club/codeathon#4]
Mỗi bạn trong nhóm tiến hành:

Fork project
Clone về local
Đọc và check môi trường thực thi
Chạy thử và chụp các ảnh giao diện
Task này giúp các bạn nắm được những tính năng mà project đang có.

@Shyren12

**Comment by Shyren12** [comment]
![image](https://user-images.githubusercontent.com/121025871/227792454-51f3cf59-cccd-4d08-be4f-9e35312a588a.png)
![image](https://user-images.githubusercontent.com/121025871/227792476-a9bec670-f7a3-42d4-b14d-694cd2656159.png)
![image](https://user-images.githubusercontent.com/121025871/227792490-1484bf0f-9b36-4eb0-9fe8-5ee5f2bd04d6.png)
![image](https://user-images.githubusercontent.com/121025871/227792506-9ea9f6d8-9d34-4f2f-a17b-3b12e3041d1c.png)
